version: '3.4'
services:
  rasa:
    image: prabhashdissanayake/rasa:latest
    working_dir: /app
    build: "./"
    volumes:
    - ./actions:/app/actions
    - ./models:/app/models
    - ./data:/app/data    
    command: "run --enable-api --cors \"*\" --port 8443 --endpoints endpoints.yml --debug"
    ports:
    - 5005:5005
    depends_on:
    - action-server
    networks:
    - all
  action-server:
    image: prabhashdissanayake/rasa:latest
    working_dir: /app
    build: "./"
    volumes:
    - ./actions:/app/actions
    ports:
    - 5055:5055
    command: "run actions --port 5056"
    networks:
    - all
networks:
  all:
    driver: bridge
