version: '3.4'
services:
  rasa-en:
    working_dir: /app
    build: "./"
    volumes:
      - ./actions:/app/actions
      - ./models:/app/models
      - ./data:/app/data    
    ports:
      - 8443:8443
    depends_on:
      - action-server
    networks:
      - all
  action-server:
    working_dir: /app
    build: "./"
    volumes:
      - ./actions:/app/actions
    ports:
      - 5056:5056
    networks:
      - all
networks:
  all:
    driver: bridge
